### ISSUE TITLE
为啥不用redis?

### ISSUE THREAD

**Issue by KIDJourney** [5aWU5ZCR5aSn5rW355qE5bGx6LS8/worker#1]
自己造memory db轮子？

**Comment by manageryzy** [comment]
这就很尴尬了，这个项目是参加中国软件杯这比赛的轮子。出题的家伙mdzz，必须用SQL数据库，必须用c，cpp，java，c sharp，禁止多机系统，禁止虚拟化和容器，禁止SSD

**Comment by manageryzy** [comment]
要是没有限制我肯定是go加redis

**Comment by KIDJourney** [comment]
好好好。。。
观摩一波
